[project]
name = "pack"
version = "0.1.0"
description = "My small project"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

requires=[
    "ply >=3.11",
]
requires-python=">=3.11"
