
precedence = [
    # ['right', ','],
    ['right', 'assign'],
    # ['right', 'extend'],
    ['right', 'lambda'],
    ['right', 'letrec'],
    ['right', 'local'],
    ['nonassoc', 'then',  'do'],
    ['nonassoc' ,'else'],
    ['left', 'or'],
    ['left', 'and', 'nand'],
    ['left', '=', 'neqs', 'eq'],
    ['left', '<', '>', 'le', 'ge'],
    ['left', '+', '-'],
    ['left', '*', '/'],
    # ['right', '(','['],
    # ['left', '(','[', ')',']'],
    # ['right', '('],
    # ['left', 'for'],
    ['right', 'not', 'UMINUS'],
    # ['left', ';'],
]
