from CONFIGS import TEST_BOOL, SHOW_TOKENS,SHOW_ENV_IMPORTS,PRINT_LEXER_TOK_LINE_AND_NR

PRINT_1_ONLY_ATTRIBUTES = False
PRINT_2_DEBUD_MODE = False
EVAL_EXPR_BEFORE_SAVE_TO_TMP=True
_TEST_FILE_NAMES = 'code/tests/all_tests.tx'
_FILE_NAMES = 'code.tx'

if TEST_BOOL:
    LOAD_FILES = _FILE_NAMES
else:
    LOAD_FILES = _TEST_FILE_NAMES

