
SHOW_ENV_IMPORTS=False
PRINT_1_ONLY_ATTRIBUTES = False
PRINT_2_DEBUD_MODE = False
EVAL_EXPR_BEFORE_SAVE_TO_TMP=True
SHOW_TOKENS=False
PRINT_LEXER_TOK_LINE_AND_NR=False
_TEST_FILE_NAMES = 'code/tests/all_tests.tx'
_FILE_NAMES = 'code.tx'
LOAD_FILES = _FILE_NAMES
LOAD_FILES = _TEST_FILE_NAMES
