
precedence = [
    ['right', 'ASSIGN'],
    # ['left', ','],
    ['right', 'LAMBDA'],
    ['right', 'LOCAL'],
    ['nonassoc', 'THEN',  'DO'],
    ['nonassoc' ,'ELSE'],
    ['left', 'OR'],
    ['left', 'AND', 'NAND'],
    ['left', '=', 'NEQS', 'EQ'],
    ['left', '<', '>', 'LE', 'GE'],
    ['left', '+', '-'],
    ['left', '*', '/'],
    ['right', 'NOT', 'UMINUS'],
]
# precedence = [
#     ['nonassoc', 'THEN'],
#     ['nonassoc', 'ELSE', 'DO', 'WHILE', 'IN'],
#     ['left', 'COMMA'],
#     ['right', 'ASSIGN'],
#     ['right', 'RIGHT_ARROW'],
#     ['left', 'OR', 'NOR', 'XOR'],
#     ['left', 'IMP'],
#     ['left', 'AND', 'NAND'],
#     ['left', 'EQS', 'NEQS', 'EQ', 'NEQ'],
#     ['left', 'LT', 'GT', 'LE', 'GE'],
#     ['left', 'PLUS', 'MINUS'],
#     ['left', 'TIMES', 'DIVIDE'],
#     ['right', 'NOT', 'UMINUS', 'UPLUS'],
#     ['right', 'LPAREN', 'LBRACKET', 'DOT'],
# ]
