
precedence = [
    ['left', ','],
    ['right', 'assign'],
    ['right', 'lambda'],
    ['right', 'local'],
    # ['right', 'dot'],
    ['nonassoc', 'then'],
    ['nonassoc', 'else', 'do'],
    ['left', 'or'],
    ['left', 'and', 'nand'],
    ['left', '=', 'neqs', 'eq'],
    ['left', '<', '>', 'le', 'ge'],
    ['left', '+', '-'],
    ['left', '*', '/'],
    # ['right', '(','['],
    ['left', '(','[', ')',']'],
    # ['left', ')',']'],
    ['right', 'not', 'UMINUS'],
]
