
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'expressionleftPLUSMINUSleftTIMESDIVIDEDIVIDE LPAREN MINUS NUMBER PLUS RPAREN TIMESexpression : expression PLUS expressionexpression : expression MINUS expressionexpression : NUMBERexpression : expression TIMES expressionexpression : expression DIVIDE expressionexpression : LPAREN expression RPAREN'
    
_lr_action_items = {'NUMBER':([0,3,4,5,6,7,],[2,2,2,2,2,2,]),'LPAREN':([0,3,4,5,6,7,],[3,3,3,3,3,3,]),'$end':([1,2,9,10,11,12,13,],[0,-3,-1,-2,-4,-5,-6,]),'PLUS':([1,2,8,9,10,11,12,13,],[4,-3,4,-1,-2,-4,-5,-6,]),'MINUS':([1,2,8,9,10,11,12,13,],[5,-3,5,-1,-2,-4,-5,-6,]),'TIMES':([1,2,8,9,10,11,12,13,],[6,-3,6,6,6,-4,-5,-6,]),'DIVIDE':([1,2,8,9,10,11,12,13,],[7,-3,7,7,7,-4,-5,-6,]),'RPAREN':([2,8,9,10,11,12,13,],[-3,13,-1,-2,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,4,5,6,7,],[1,8,9,10,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression_plus','f_expression_parser.py',11),
  ('expression -> expression MINUS expression','expression',3,'p_expression_minus','f_expression_parser.py',15),
  ('expression -> NUMBER','expression',1,'p_expression_num','f_expression_parser.py',19),
  ('expression -> expression TIMES expression','expression',3,'p_expression_times','f_expression_parser.py',23),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_div','f_expression_parser.py',27),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_paren','f_expression_parser.py',31),
]
