# NOT USED ANYMORE
[project]
name = "src"
version = "1.0.0"
description = "Interpreter--und-Compilerbau"
# description = "My small project"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

# requires=[
#     "ply >=3.11",
# ]
requires-python=">=3.11"
